
services:
  mysql:
    image: mysql:latest
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  seed:
    build: ./backend
    command: ["python", "models.py"]
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tasks_db
    restart: "no"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      seed:
        condition: service_completed_successfully
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tasks_db
    ports:
      - "5000:5000"

volumes:
  mysql_data:
